version: "3.8"

services:
  front:
    image: "node:22-alpine"
    working_dir: /app
    volumes:
      - /web-app/node_modules
      - ./web-app:/app
    ports:
      - "80:80"
    command: sh -c "npm install && npm run dev"